import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./componente/navbar/Navbar";
import RegisterModal from "./componente/modal/RegisterModal";
import ToasterProvider from "./providers/toasterProvider";
import LoginModal from "./componente/modal/LoginModal";
import getCurrentUser from "./accion/getCurrentUser";
import RentModal from "./componente/modal/RentModal";
import BuscarModal from "./componente/modal/BuscarModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Airbnb",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getCurrentUser();


  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ToasterProvider/>
        <BuscarModal/>
        <RentModal/>
        <RegisterModal/>
        <LoginModal/>
        <Navbar currentUser = {currentUser}/>
        <section className="pb-20 pt-28">
          {children}
        </section> 
      </body>
    </html>
  );
}
